### ISSUE TITLE
Hi Daokuan

### ISSUE THREAD

**Issue by Sprinter1999** [dnvbai98/LSG_master#1]
I'm the author of FedLSR  (CIKM'22). If convenient, may I add your wechat for discussion about the Federated Noisy Label Learning. Since I cannot find your email within the paper FedLSG, I just issue this repo : ) 

Thank you

**Comment by dnvbai98** [comment]
Sure，it is my pleasure.My WeChat is 18228037507.


---- Replied Message ----
| From | ***@***.***> |
| Date | 07/22/2023 16:25 |
| To | DaokuanBai/LSG_master ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [DaokuanBai/LSG_master] Hi Daokuan (Issue #1) |

I'm the author of FedLSR (CIKM'22). If convenient, may I add your wechat for discussion about the Federated Noisy Label Learning. Since I cannot find your email within the paper FedLSG, I just issue this repo : )

Thank you
